### ISSUE TITLE
Rename npm package to moneyd-xrp

### ISSUE THREAD

**Issue by michielbdejong** [interledgerjs/moneyd-xrp#17]
This repo still squats the 'moneyd' npm package name, which maybe we should reserve for https://github.com/interledgerjs/moneyd-trust/issues/1 - or maybe stop using it and just use:

* moneyd-trust (never settle, just trust)
* moneyd-xrp (settle over paychan over xrp)
* moneyd-lnd (settle over lightning over btc)
* moneyd-eth (settle over machinomy over ethereum)

**Comment by sharafian** [comment]
DJ's refactor is going to be one moneyd package with pluggable logic for other currencies, so I think this issue can be closed
