### ISSUE TITLE
Running a node

### ISSUE THREAD

**Issue by benjamintrosen** [interledgerjs/moneyd-xrp#19]
Hi All, 
How do I go about running rode v8.9.4 or higher as requested under the system requirements on the instructions of this page? Let me know. A thank you to Ben Sharafian for providing some great tips and pointing me to Moneyd, btw!

**Comment by dappelt** [comment]
You can install node from https://nodejs.org/en/ or use [nvm](https://github.com/creationix/nvm) to easily install and switch between node versions.

**Comment by sharafian** [comment]
I think this can be closed
