### ISSUE TITLE
Accepting connections only from localhost

### ISSUE THREAD

**Issue by dappelt** [interledgerjs/moneyd-xrp#2]
moneyd is supposed to accept connections only from localhost by default. To achieve this, you can bind the websocket server to localhost like so:

```js
const plugin = new IlpPluginMiniAccounts({
  wsOpts: {
    host: '127.0.0.1',
    port: 80
  }
})
```

However, we should prevent websocket connections initiated from a browser to connect to moneyd. Otherwise, a malicious site could serve some JS code that opens a websocket to localhost and steal money. Something like:
```
Local WebSocket Server            Browser            Evil Web Server
at ws://localhost:1234                               at http://evil.tld
        |                            |                       |
        |                            |------[GET /]--------->|
        |                            |<-----[HTML+EvilJS]----|
        |<--[connect ws://local...]--|                       |
        |<----[some communication]-->|                       |
        |                            |----[evil forward]---->|
        |                            |                       |
```

Rejecting websocket connections initiated from browsers should prevent such attacks. This can be achieved by checking for the origin header: https://github.com/interledgerjs/ilp-plugin-mini-accounts/blob/da-listen-localhost-only/index.js#L52-L56

**Comment by sharafian** [comment]
Closed by #6

**Comment by dappelt** [comment]
This issue is not fully resolved yet. #6 is the first part of the solution, https://github.com/interledgerjs/ilp-plugin-mini-accounts/pull/13 is the second.

**Comment by sharafian** [comment]
oops. I wasn’t able to get the chrome extension to remove the origin header. Adding the URL to permissions appeared to have no effect. Could you take a stab at it?

**Comment by dappelt** [comment]
It seems chrome extensions only omit the origin header for XHR requests. We will have to use a whitelist of allowed chrome extension ids.

**Comment by sharafian** [comment]
That might be difficult; I believe the extension ID changes every time the code is modified. Could we just allow any extension to access it?

**Comment by emschwartz** [comment]
It looks like you can [set it so it doesn't change](https://stackoverflow.com/questions/31422195/keep-chrome-extension-id-same-during-development), at least during development. That should be less of an issue once it's published anyway

**Comment by sharafian** [comment]
that also raises barriers to entry if anyone else wants to make an extension. Anybody who wants to make an ILP enabled extension should be able to without making their users muck around with the moneyd config.

**Comment by dappelt** [comment]
> That might be difficult; I believe the extension ID changes every time the code is modified. Could we just allow any extension to access it?

@sharafian here is a [description](https://stackoverflow.com/questions/21497781/how-to-change-chrome-packaged-app-id-or-why-do-we-need-key-field-in-the-manifest/21500707#21500707) how to generate an extension ID.

If we whitelist all chrome extension then any extension could spend a user's funds without asking for permission.

> [...] without making their users muck around with the moneyd config.
If in the future usability becomes a concern then we could have a small configuration UI for moneyd.

**Comment by dappelt** [comment]
Whitelist implementation https://github.com/interledgerjs/ilp-plugin-mini-accounts/tree/da-listen-localhost-only

**Comment by emschwartz** [comment]
Actually if the vision for moneyd is that any program running on your machine would be able to access it, it might be fine to count browser extensions in that. The thing we would want to avoid though would be for any website you go to to be able to access moneyd from javascript

**Comment by dappelt** [comment]
The security model of browser extensions is more similar to that of websites than to local executables. The same-origin policy and other browser security mechanisms apply to extensions just as for websites and extensions are by default not allowed to do most of the things local executables can do.

And that is for good reason. Your browser and its extensions along with it are the single most exposed piece of software running on your computer. Websites can interact with extensions and many of the typical web vulnerabilities, especially XSS, are a threat to extensions as well. By making moneyd available to ANY extension, you elevate a comparable harmless XSS vulnerability to a vulnerability that has full access to your money. In other words, an extension that was never intended by its developer to access moneyd and that was never granted permission by the user will be able to steal funds.

If you want my seal of approval, these requirements should be met for an extension to have access to moneyd:
- Only extensions that require access to moneyd should be able to interact with it.
- There should be a defined method for an extension to indicate that they require access to moneyd (preferably via a config file like `manifest.json`).
- A user has to give his consent before an extension can access moneyd.

I strongly recommend against allowing all chrome extensions. This is a bad idea, don't do it.

**Comment by emschwartz** [comment]
Makes sense. Then maybe the way to think about it would be that there might be a single chrome extension that pairs with moneyd and then exposes payment functionality within the browser. That extension would control which websites are allowed to send payments and how much.

**Comment by sharafian** [comment]
That would make for a very bad user experience, if you need to manually approve every site you go to before it can get paid. The entire purpose of the chrome extension is to work in the background and provide you a better experience online without the user needing to intervene in any way.

With the current extension, websites also don't send payments directly; they just tell the browser where to pay them and the browser decides how much and how often.

Although, because ordinary end users may not want to run a daemon on their machine, we'll eventually want the extension to connect to a remote ILP provider (like the micro-payments flat rate provider) instead of a local one.

Could we just add a `--unsafe-allow-extensions` flag that's disabled by default? And we could also add a stricter `--allow-origin` flag that allows a particular origin to connect to moneyd, so you could add all the the `chrome-extension://.....` URLs you need manually.

That way if a developer wants to play around with small amounts they can use the unsafe flag. If they want to be more secure about it then they can do the `--allow-origin` version. And by default nothing with an `Origin` would be allowed.

**Comment by emschwartz** [comment]
> That would make for a very bad user experience, if you need to manually approve every site you go to before it can get paid.

That's not what I'm suggesting. I'm suggesting that you would have a single extension that could automatically manage which websites are allowed to pay.

> The entire purpose of the chrome extension is to work in the background and provide you a better experience online without the user needing to intervene in any way.

Which is why you probably don't need to plan for many extensions accessing moneyd.

**Comment by emschwartz** [comment]
One way to do it would be that when a new website asks for permission to spend your money it could use something like https://github.com/mikaelbr/node-notifier to ask the user if they want to grant it permission

**Comment by adrianhopebailie** [comment]
> That would make for a very bad user experience, if you need to manually approve every site you go to before it can get paid

That is pretty much the security model for the web and any "powerful features". They are only available under a secure context and often require the user's permission per origin.

That said, I'd hope that the extension is just a bootstrap until this functionality is built into the browser through the Payment Request API at which point it will inherit the permission model already built into that.

Given that this is experimental I would recommend conservative defaults with the ability to override them for developers (as suggested by @sharafian).

Another thing to consider is exposing moneyd to applications using a more secure interface like a socket. I'd expect browsers to use this directly in future.

In the interim, moneyd could offer a WebSocket that is mostly only for browser hosted applications (websites and extensions) and then require some more explicit authentication through that interface. This should roughly resemble the Web security model as implemented in browsers.

Example:

1. Website/Extension requests ability to pay through moneyd via a call to WebSocket on `localhost`
2. Moneyd shows dialogue to user requesting permission to authorize the origin to request payments
3. If user says "Yes" then whitelist that origin (maybe with a bandwidth limit)
4. If user says "No" then blacklist that origin until user manually edits moneyd config.

In future the browser handles this interaction and uses the less locked down socket interface to moneyd. (Possible to experiment with this on Android already today I believe)

Unfortunately security and usability are always in conflict. When it comes to people's money I think we need to err on the side of security.

**Comment by dappelt** [comment]
> Could we just add a --unsafe-allow-extensions flag that's disabled by default? And we could also add a stricter --allow-origin flag that allows a particular origin to connect to moneyd, so you could add all the the chrome-extension://..... URLs you need manually.

@sharafian I implemented these flags here https://github.com/interledgerjs/moneyd-xrp/pull/12
