### ISSUE TITLE
Running into  [RippledError(noNetwork)] when running testnet

### ISSUE THREAD

**Issue by andywong418** [interledgerjs/moneyd-xrp#25]
Currently when I try running the testnet I'm getting a connector:app error [RippledError(noNetwork)]. Does this mean that my testnet node is down?

**Comment by sharafian** [comment]
From [the Ripple API docs](https://ripple.com/build/rippled-apis/#error-responses):

> `noNetwork` - The server is having trouble connecting to the rest of the XRP Ledger peer-to-peer network (and is not running in stand-alone mode)

So I think you're right; your node can't reach the rest of the network. I'm not having any problems with `wss://s.altnet.rippletest.net:51233` so I think it's on your end.

You may want to ask in https://github.com/ripple/rippled ; I think they'll have more advice to offer on how to configure and run a testnet node.

**Comment by andywong418** [comment]
Yeah it turns out there was a Rippled network error on that day
