### ISSUE TITLE
Error when blocking browser should explain how to fix it

### ISSUE THREAD

**Issue by justmoon** [interledgerjs/moneyd-xrp#26]
I was running moneyd and got the following error:

```
Closing a websocket connection received from a browser. Origin is chrome-extension://fakjpmebfmpdbhpnddiokemempckoejk
```

After some googling, I figured out that I needed to set the `--unsafe-allow-extensions` flag. The error message should just tell you that you can set that flag to bypass the error. -> no more googling necessary.

**Comment by dappelt** [comment]
I added a message.

Note that `--unsafe-allow-extensions` should only be used for development. `--allow-origin <origin>` is the recommended way for whitelisting origins.
